@startuml

class User {
  - id: String
  - username: String
  - password: String
  - email: String
  - phoneNumber: String
  --
  + User();
  + User(username: String, password: String, email: String, phoneNumber: String);
  + Getter and Setter
}

class UserService {
    + getUserById(userId: String);
    + getAllUsers();
}

class AuthService {
    + login(username: String, password: String);
    + register(username: String, password: String, email: String, phoneNumber: String);
    + changePassword(userId: String, newPassword: String, confirmNewPassword: String);

}
@enduml